version: 1.1.{build}
image: Visual Studio 2017
configuration: Release

# Build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache'  # NuGet v3

# Enable patching of AssemblyInfo.* files
init:
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_informational_version: '$(APPVEYOR_BUILD_VERSION)'

build:
  verbosity: minimal

after_build:
  - ps: nuget pack build\nuspecs\UmbMapper.nuspec -version "$env:PackageVersion"
  - ps: nuget pack build\nuspecs\UmbMapper.NuPickers.nuspec -version "$env:PackageVersion"
  - ps: nuget pack build\nuspecs\UmbMapper.Archetype.nuspec -version "$env:PackageVersion"
  - ps: nuget pack build\nuspecs\UmbMapper.PublishedContentModelFactory.nuspec -version "$env:PackageVersion"

artifacts:
  - path: 'UmbMapper*.nupkg'

# deploy:
#   - provider: NuGet
#     server: https://www.myget.org/F/umbmapper/api/v2/package
#     symbol_server: https://www.myget.org/F/umbmapper/symbols/api/v2/package
#     api_key:
#       secure: fz0rUrt3B1HczUC1ZehwVsrFSWX9WZGDQoueDztLte9/+yQG+BBU7UrO+coE8lUf
#     artifact: /.*\.nupkg/
#     on:
#       branch: develop

#   - provider: NuGet
#     api_key:
#       secure: kHataLiMb9nmJEdwBE4BTXvA4nOpoD3Fw14zVeDP6Vs0ZXpL7c8qeegMv/jMZECP
#     skip_symbols: false
#     artifact: /.*\.nupkg/
#     on:
#       branch: master
#       appveyor_repo_tag: true        # deploy on tag push only

# prevent the double build when a branch has an active PR
skip_branch_with_pr: true